/**
 * Uzhavan 360 - Shared State Machine Constants
 * Level 1 Architecture Reference: Section 16, 17, 18, 20, 21, 22
 */

// Phase 1: Buyer Request States
export const REQUEST_STATES = Object.freeze({
  REQUESTED: 'REQUESTED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
  QUANTITY_PENDING: 'QUANTITY_PENDING',
  RESERVED: 'RESERVED',
  CANCELLED: 'CANCELLED'
});

// Phase 2: Order & Reservation States
export const ORDER_STATES = Object.freeze({
  RESERVED: 'RESERVED',
  PREPARING: 'PREPARING',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  COMPLETED: 'COMPLETED',
  COMPLETED_PARTIAL: 'COMPLETED_PARTIAL',
  NO_SHOW: 'NO_SHOW',
  CANCELLED_BY_BUYER: 'CANCELLED_BY_BUYER',
  CANCELLED_BY_FARMER: 'CANCELLED_BY_FARMER',
  EXPIRED: 'EXPIRED'
});

// Double-Entry Inventory Ledger Transaction Types
export const INVENTORY_TRANSACTION_TYPES = Object.freeze({
  // Level 4 Core Ledger Reasons
  NEW_HARVEST: 'NEW_HARVEST',
  RESERVATION: 'RESERVATION',
  RESERVATION_RELEASE: 'RESERVATION_RELEASE',
  SALE: 'SALE',
  OFF_PLATFORM_SALE: 'OFF_PLATFORM_SALE',
  STOCK_CORRECTION: 'STOCK_CORRECTION',
  ADJUSTMENT: 'ADJUSTMENT',

  // Level 3 Aliases for backward compatibility
  INITIAL_LISTING: 'INITIAL_LISTING',
  RESERVE_STOCK: 'RESERVE_STOCK',
  RELEASE_RESERVATION: 'RELEASE_RESERVATION',
  CONFIRM_SALE: 'CONFIRM_SALE',
  OFFLINE_SALE: 'OFFLINE_SALE',
  STOCK_CORRECTION_LOSS: 'STOCK_CORRECTION_LOSS',
  BATCH_ADDITION: 'BATCH_ADDITION'
});

// Freshness Tiers
export const FRESHNESS_TIERS = Object.freeze({
  FRESH_HARVEST: 'FRESH_HARVEST',
  NORMAL: 'NORMAL',
  SELL_SOON: 'SELL_SOON'
});

// Market Demand Trends
export const DEMAND_TRENDS = Object.freeze({
  INCREASING: 'INCREASING',
  STABLE: 'STABLE',
  DECREASING: 'DECREASING'
});
